
CREATE (carrierglobal:Organization { name: "Carrier Global", did: "carrier-global"})
CREATE (transnationalgoods:Organization { name: "Trans-National Goods Inc", did: "trans-national-goods"})
CREATE (ironinspect:Organization { name: "Iron Inspect Corp", did: "iron-inspect"})
CREATE (alloyinspectors:Organization { name: "Alloy Inspectors", did: "alloy-inspectors"})
CREATE (steelrollinc:Organization { name: "Steel Roll Inc", did: "steel-roll-inc"})
CREATE (muricacars:Organization { name: "Murica Cars", did: "murica-cars"})
CREATE (panelstampers:Organization { name: "Panel Stampers", did: "panel-stampers"})
CREATE (genericmotors:Organization { name: "Generic Motors", did: "generic-motors"})
CREATE (stainlessexperts:Organization { name: "Stainless Experts", did: "stainless-experts"})
CREATE (steelmfg:Organization { name: "Steel Mfg", did: "steel-mfg"})
CREATE (enginesinc:Organization { name: "Engines Inc", did: "engines-inc"})
CREATE (ironcore:Organization { name: "Iron Core", did: "iron-core"})

CREATE (vc1:VerifiableCredential:BillOfLading { name: "BL 1", id: "bl1"})
CREATE (vc1)-[vc1a:ISSUER]->(transnationalgoods)
CREATE (vc1)-[vc1b:SHIPPER]->(steelrollinc)
CREATE (vc1)-[vc1c:CONSIGNEE]->(muricacars)
CREATE (vc2:VerifiableCredential:BillOfLading { name: "BL 2", id: "bl2"})
CREATE (vc2)-[vc2a:ISSUER]->(transnationalgoods)
CREATE (vc2)-[vc2e:SHIPPER]->(steelrollinc)
CREATE (vc2)-[vc2f:CONSIGNEE]->(panelstampers)
CREATE (vc3:VerifiableCredential:BillOfLading { name: "BL 3", id: "bl3"})
CREATE (vc3)-[vc3a:ISSUER]->(carrierglobal)
CREATE (vc3)-[vc3e:SHIPPER]->(steelrollinc)
CREATE (vc3)-[vc3f:CONSIGNEE]->(genericmotors)
CREATE (vc4:VerifiableCredential:BillOfLading { name: "BL 4", id: "bl4"})
CREATE (vc4)-[vc4a:ISSUER]->(transnationalgoods)
CREATE (vc4)-[vc4b:SHIPPER]->(steelmfg)
CREATE (vc4)-[vc4c:CONSIGNEE]->(genericmotors)
CREATE (vc5:VerifiableCredential:BillOfLading { name: "BL 5", id: "bl5"})
CREATE (vc5)-[vc5a:ISSUER]->(carrierglobal)
CREATE (vc5)-[vc5e:SHIPPER]->(steelmfg)
CREATE (vc5)-[vc5f:CONSIGNEE]->(enginesinc)
CREATE (vc6:VerifiableCredential:BillOfLading { name: "BL 6", id: "bl6"})
CREATE (vc6)-[vc6a:ISSUER]->(transnationalgoods)
CREATE (vc6)-[vc6e:SHIPPER]->(steelmfg)
CREATE (vc6)-[vc6f:CONSIGNEE]->(ironcore)

CREATE (mtr1:VerifiableCredential:MillTestReport { name: "MTR 1", id: "mtr1"})
CREATE (mtr1)-[mtr1a:ISSUER]->(stainlessexperts)
CREATE (mtr1)-[mtr1b:MANUFACTURER]->(steelrollinc)
CREATE (mtr2:VerifiableCredential:MillTestReport { name: "MTR 2", id: "mtr2"})
CREATE (mtr2)-[mtr2a:ISSUER]->(ironinspect)
CREATE (mtr2)-[mtr2b:MANUFACTURER]->(steelrollinc)
CREATE (mtr3:VerifiableCredential:MillTestReport { name: "MTR 3", id: "mtr3"})
CREATE (mtr3)-[mtr3a:ISSUER]->(alloyinspectors)
CREATE (mtr3)-[mtr3b:MANUFACTURER]->(steelrollinc)
CREATE (mtr4:VerifiableCredential:MillTestReport { name: "MTR 4", id: "mtr4"})
CREATE (mtr4)-[mtr4a:ISSUER]->(stainlessexperts)
CREATE (mtr4)-[mtr4b:MANUFACTURER]->(steelmfg)
CREATE (mtr5:VerifiableCredential:MillTestReport { name: "MTR 5", id: "mtr5"})
CREATE (mtr5)-[mtr5a:ISSUER]->(alloyinspectors)
CREATE (mtr5)-[mtr5b:MANUFACTURER]->(steelmfg)
CREATE (mtr6:VerifiableCredential:MillTestReport { name: "MTR 6", id: "mtr6"})
CREATE (mtr6)-[mtr6a:ISSUER]->(stainlessexperts)
CREATE (mtr6)-[mtr6b:MANUFACTURER]->(steelmfg)

CREATE (ci1:VerifiableCredential:CommercialInvoice { name: "CI 1", id: "ci1"})
CREATE (ci1)-[ci1a:ISSUER]->(steelrollinc)
CREATE (ci1)-[ci1b:BUYER]->(muricacars)
CREATE (ci2:VerifiableCredential:CommercialInvoice { name: "CI 2", id: "ci2"})
CREATE (ci2)-[ci2a:ISSUER]->(steelrollinc)
CREATE (ci2)-[ci2b:BUYER]->(panelstampers)
CREATE (ci3:VerifiableCredential:CommercialInvoice { name: "CI 3", id: "ci3"})
CREATE (ci3)-[ci3a:ISSUER]->(steelrollinc)
CREATE (ci3)-[ci3b:BUYER]->(genericmotors)
CREATE (ci4:VerifiableCredential:CommercialInvoice { name: "CI 4", id: "ci4"})
CREATE (ci4)-[ci4a:ISSUER]->(steelmfg)
CREATE (ci4)-[ci4b:BUYER]->(genericmotors)
CREATE (ci5:VerifiableCredential:CommercialInvoice { name: "CI 5", id: "ci5"})
CREATE (ci5)-[ci5a:ISSUER]->(steelmfg)
CREATE (ci5)-[ci5b:BUYER]->(enginesinc)
CREATE (ci6:VerifiableCredential:CommercialInvoice { name: "CI 6", id: "ci6"})
CREATE (ci6)-[ci6a:ISSUER]->(steelmfg)
CREATE (ci6)-[ci6b:BUYER]->(ironcore)

CREATE (iti1:VerifiableCredential:IntentToImport { name: "ITI 1", id: "iti1"})
CREATE (iti1)-[iti1a:ISSUER]->(muricacars)
CREATE (iti2:VerifiableCredential:IntentToImport { name: "ITI 2", id: "iti2"})
CREATE (iti2)-[iti2a:ISSUER]->(panelstampers)
CREATE (iti3:VerifiableCredential:IntentToImport { name: "ITI 3", id: "iti3"})
CREATE (iti3)-[iti3a:ISSUER]->(genericmotors)
CREATE (iti4:VerifiableCredential:IntentToImport { name: "ITI 4", id: "iti4"})
CREATE (iti4)-[iti4a:ISSUER]->(genericmotors)
CREATE (iti5:VerifiableCredential:IntentToImport { name: "ITI 5", id: "iti5"})
CREATE (iti5)-[iti5a:ISSUER]->(enginesinc)
CREATE (iti6:VerifiableCredential:IntentToImport { name: "ITI 6", id: "iti6"})
CREATE (iti6)-[iti6a:ISSUER]->(ironcore)
